// <auto-generated />
using System;
using DirectoryService.Infrastructure.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DirectoryService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DirectoryService.Domain.Entities.EducationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationDocuments");
                });

            modelBuilder.Entity("DirectoryService.Domain.Entities.EducationDocumentNextLevel", b =>
                {
                    b.Property<Guid>("EducationDocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("integer");

                    b.HasKey("EducationDocumentId", "EducationLevelId");

                    b.HasIndex("EducationLevelId");

                    b.ToTable("EducationDocumentNextLevels");
                });

            modelBuilder.Entity("DirectoryService.Domain.Entities.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");
                });

            modelBuilder.Entity("DirectoryService.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("DirectoryService.Domain.Entities.ImportedDirectroriesStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ImportTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DirectoryImportStatistics");
                });

            modelBuilder.Entity("DirectoryService.Domain.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EducationForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("integer");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("DirectoryService.Domain.Entities.EducationDocumentNextLevel", b =>
                {
                    b.HasOne("DirectoryService.Domain.Entities.EducationDocument", "EducationDocument")
                        .WithMany("NextLevels")
                        .HasForeignKey("EducationDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DirectoryService.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany("DocumentLinks")
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationDocument");

                    b.Navigation("EducationLevel");
                });

            modelBuilder.Entity("DirectoryService.Domain.Entities.ImportedDirectroriesStatistic", b =>
                {
                    b.OwnsOne("DirectoryService.Domain.Entities.ImportedDirectories", "Imported", b1 =>
                        {
                            b1.Property<Guid>("ImportedDirectroriesStatisticId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DocumentTypes")
                                .HasColumnType("integer");

                            b1.Property<int>("EducationLevels")
                                .HasColumnType("integer");

                            b1.Property<int>("Faculties")
                                .HasColumnType("integer");

                            b1.Property<int>("Programs")
                                .HasColumnType("integer");

                            b1.HasKey("ImportedDirectroriesStatisticId");

                            b1.ToTable("DirectoryImportStatistics");

                            b1.WithOwner()
                                .HasForeignKey("ImportedDirectroriesStatisticId");
                        });

                    b.Navigation("Imported")
                        .IsRequired();
                });

            modelBuilder.Entity("DirectoryService.Domain.Entities.Program", b =>
                {
                    b.HasOne("DirectoryService.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DirectoryService.Domain.Entities.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("DirectoryService.Domain.Entities.EducationDocument", b =>
                {
                    b.Navigation("NextLevels");
                });

            modelBuilder.Entity("DirectoryService.Domain.Entities.EducationLevel", b =>
                {
                    b.Navigation("DocumentLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
